### ISSUE TITLE
Azure SQL -> Should be SQL Server, there's no Azure SQL used in this sample project.

### ISSUE THREAD

**Issue by seantleonard** [Azure-Samples/azure-sql-library-app-blazor#12]
Instances of Azure SQL mentioned in README and sample title should reflect that this sample uses SQL Server 2022 (Linux). I'm missing where Azure SQL is used. I supposed you'd need to update the Readme to indicate that you could publish the dacpac to Azure SQL if desired. Then document where and how to update the DB connection string in the sample to point to Azure SQL and not localhost.

**Comment by croblesm** [comment]
Thanks for the feedback! This issue was partially fixed on this commit: 06ff3078ffe49284f0d95fdcc66fcd6b20f5e994

The SQL Database project is created for an Azure SQL Database target, thus the database schema is Azure SQL Database compatible. I added a note to explain this situation [here](https://github.com/Azure-Samples/azure-sql-library-app-blazor/blob/adc4a9f3a1d24b253cce0c3861123672282746a5/README.md?plain=1#L91).
